# Default values for dask.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# nameOverride: dask

scheduler:
  name: scheduler
  image: "daskdev/dask"
  imageTag: "latest"
  replicas: 1
  component: "dask-scheduler"
  serviceType: "LoadBalancer"
  servicePort: 8786
  containerPort: 8786
  resources: {}
  condaPackages: >-
  pipPackages: >-
  limits:
    cpu: 2
    memory: 7.5G
  requests:
    cpu: 2
    memory: 7.5G

webUI:
  name: webui
  servicePort: 80
  containerPort: 8787

worker:
  name: worker
  image: "daskdev/dask"
  imageTag: "latest"
  replicas: 3
  component: "dask-worker"
  containerPort: 8081
  resources: {}
  condaPackages: >-
    # numba
    # xarray
  pipPackages: >-
    # gcsfs
    # s3fs
    # adlfs
    # dask-ml
  limits:
    cpu: 1
    memory: 3.5G
  requests:
    cpu: 1
    memory: 3.5G

jupyter:
  name: jupyter
  image: tomgrek/jupyter #"daskdev/dask-notebook"
  imageTag: "latest"
  replicas: 1
  component: "jupyter-notebook"
  volume: vol-0c6c84e29fd2f9d64
  serviceType: "LoadBalancer"
  servicePort: 80
  containerPort: 8888
  password: 'sha1:5110b9bc2713:514fdc9340022f644820284ab06fd120896d3e8d'
  resources: {}
  condaPackages: >-
    # numba
    # xarray
  pipPackages: >-
    # gcsfs
    # s3fs
    # adlfs
    # dask-ml
  limits:
    cpu: 2
    memory: 7.5G
  requests:
    cpu: 2
    memory: 7.5G
