# Default values for dask.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# nameOverride: dask

scheduler:
  name: scheduler
  image: "tomgrek/daskworker"
  imageTag: "latest"
  replicas: 1
  component: "dask-scheduler"
  serviceType: "LoadBalancer"
  servicePort: 8786
  containerPort: 8786
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  resources: {}
  condaPackages: >-
  pipPackages: >-
  limits:
    cpu: 3
    memory: 4.5G
  requests:
    cpu: 3
    memory: 4.5G

webUI:
  name: webui
  servicePort: 80
  containerPort: 8787
  serviceType: "LoadBalancer"

worker:
  name: worker
  image: "tomgrek/daskworker"
  imageTag: "latest"
  replicas: 6
  component: "dask-worker"
  containerPort: 8081
  resources: {}
  condaPackages: >-
  pipPackages: >-
  limits:
    cpu: 2
    memory: 16G
  requests:
    cpu: 2
    memory: 16G

jupyter:
  name: jupyter
  image: tomgrek/jupyter #"daskdev/dask-notebook"
  imageTag: "latest"
  replicas: 1
  component: "jupyter-notebook"
  volume: vol-0c6c84e29fd2f9d64
  serviceType: "LoadBalancer"
  servicePort: 80
  containerPort: 8888
  password: 'sha1:5110b9bc2713:514fdc9340022f644820284ab06fd120896d3e8d'
  resources: {}
  condaPackages: >-
    awscli
    feather-format
  pipPackages: >-
    boto3
    s3fs
    pyarrow
    feather-format
    # adlfs
    # dask-ml
  limits:
    cpu: 4
    memory: 31G
  requests:
    cpu: 4
    memory: 31G
